### ISSUE TITLE
Can't filter by multiple values with python list[]

### ISSUE THREAD

**Issue by Kyle772** [igdb/igdb_api_python#8]
Not sure if I'm just doing something wrong but I'm trying to filter by 

```
'filters': {
    "[first_release_date][in]": [dtpast, dtfuture]
}
```

and I keep getting errors. It works with each value individually but not the range.

**Comment by sharpless512** [comment]
Hi @Kyle772 ,

I presume you want a list of games that are released within a certain time period.

```
'filters': {
    "[first_release_date][gt]": dtpast,
    "[first_release_date][lt]": dtfuture,
}
```

Postman url example: 
`https://api-2445582011268.apicast.io/games/?fields=name,first_release_date&filter[first_release_date][gt]=1487203100000&filter[first_release_date][lt]=1487203200001
`

Is that what you where trying to do?

**Comment by Kyle772** [comment]
That is! I tried that but ran into an error. Maybe it was a typo? The documentation calls for an array which is why I was confused on that. I appreciate the help!

**Comment by Kyle772** [comment]
```
result = igdb.games({
                'fields': ['name', 'popularity', 'cover', 'id', 'game', 'slug'],
                'limit': 25,
                'order': 'first_release_date:desc',
                'filters': {
                    "[game_modes][any]": 2,
                    "[rating][gte]": 60,
                    "[first_release_date][gte]": dtp,
                    "[first_release_date][lte]": dtf
                }
            })
```

Actually repopening. I assumed it was a typo but I'm not getting anything back for some reason with that additional line. Above is the request.

**Comment by Kyle772** [comment]
Found the issue. I was using a datetime object and it was throwing off the filter. 

games/?fields=name,popularity,cover,id,game,slug&filter[game_modes][any]=2&filter[first_release_date][gte]=**2016-09-28T18:33:09.016011**&filter[first_release_date][lte]=**0088-09-28T18:33:09.016011**&filter[rating][gte]=60&order=first_release_date:desc&limit=25

**Comment by sharpless512** [comment]
@Kyle772 great that you found the issue!
