### ISSUE TITLE
Remove print

### ISSUE THREAD

**Issue by krazyjakee** [igdb/igdb_api_python#9]
I don't think this is necessary: https://github.com/igdb/igdb_api_python/blob/master/igdb_api_python/igdb.py#L60

**Comment by WolfgangPires** [comment]
At least make it "toggleable", if it's necessary for debugging.

**Comment by zirekyle** [comment]
Another option is to use the logging module and log to the "info" level, which could then be filtered out by setting the log level in any other code using this module.
